information = {
    "Dendrites": "Dendrites are the leading components of a neuron that branches into more dendrites. These tree-looking parts are responsible for receiving signals from other neurons, allowing you to move, think, and sense/feel different things.",
    "Nucleus": "The nucleus in neurons is spherical and ranges in diameter from 3 to 18 micrometers depending on the size of the neuron. Neurons with long axons have a larger cell body and nucleus. ",
    "Cell Body": "The cell body is the core section of the neuron (also known as the soma). The cell body contains genetic information, maintains the neuron's structure, and provides energy to drive activities. Like other cell bodies, a neuron's soma contains a nucleus and specialized organelles.",
    "Axon": "The axon is a slender nerve cell projection that carries electrical impulses away from the cell body. It is covered by the axolemma, with axoplasm inside. Axons often branch, ending in telodendria, whose swollen tips form axon terminals. These terminals create synapses by connecting to other neurons, muscles, or glands.",
    "Schwann Cells": "Schwann cells are neuronal support cells that produce an insulating myelin sheath that surrounds axons of the peripheral nervous system and promote neuronal conduction by propagating electrical signals through often long peripheral nerves.",
    "Myelin Sheath": "The myelin sheath is like a train. As a train encloses passengers and travels safely to a destination, the myelin sheath is a coating that helps to allow messages from the brain travel around your nerves and body safely. Without it, your body might not function properly as different body parts would not receive the information it needs.",
    "Node of Ranvier": "The Node of Ranvier is a small gap between sections of myelin, which is a protective layer around nerve fibers. These gaps help speed up the electrical signals that travel along nerves by allowing the signal to jump from one node to the next. This makes the process of sending messages in the nervous system much faster. It's important for quick responses, like when you touch something hot and quickly move your hand away.",
    "Axon Terminals": "The axon terminals are what connect the nerve cell to other nerve cells. Through axons and its terminals, signals are transported and sent to other nerve cells. Think of them as a charger. When you connect a power source to your phone using a charger, energy is sent from the power source, allowing your phone to charge and function.",
}